branches:
  only:
    - master

language: 
  - c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq 
  - sudo apt-get install -y irssi-dev libssl-dev cmake
  - cd ${TRAVIS_BUILD_DIR}
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
  - tar xf lcov_1.13.orig.tar.gz
  - sudo make -C lcov-1.13/ install
  - gem install coveralls-lcov
  - lcov --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  # init coverage to 0 (optional)
  - lcov --directory . --zerocounters

script:
  - cmake .
  - make 
  - ctest --verbose
  
after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
