env:
  global:
  - secure: EYCRIQEAVnQSgAUEaZb2WSXh5OQ0Xd12IL5kt6HPpIFQu3WoMiH/Mfn7GFXDkcIRoBDUuLn02BQyZWE2MjHEp9ua/6wg0ne6a8p9GZ5kWeajDI1Q1cNuXzke4oZLFuVQd8bteOH5ylvWAsbPFsdizvIJcKxE2bwiI+FCNXGvc6o=
before_install:
- sudo apt-get update -qq
- sudo apt-get install -y irssi-dev libssl-dev cmake
addons:
  coverity_scan:
    project:
      name: falsovsky/FiSH-irssi
      description: irssi FiSH plugin
    notification_email: falsovsky@gmail.com
    build_command_prepend: cmake .
    build_command: make
    branch_pattern: coverity_scan
branches:
  only:
  - master
  - testing
  - coverity_scan
language:
- c
compiler:
- gcc
- clang
script:
- cmake .
- make
