language: 
  - c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq 
  - sudo apt-get install -y irssi-dev libssl-dev
script:
  - ./autogen.sh
  - ./configure --with-irssi=/usr/include/irssi
  - make 
